#if defined _pistol_timer_included
 #endinput
#endif
#define _pistol_timer_included

#define TEAM_ALLIES 2
#define TEAM_AXIS 3
#define ALLIES_PISTOL_IN_ARRAY 1
#define AXIS_PISTOL_IN_ARRAY 2
#define ALLIES_PISTOL_CLASS_NAME "weapon_colt"
#define AXIS_PISTOL_CLASS_NAME "weapon_p38"
#define ALLIES_BULLETS_FOR_PISTOL 14
#define AXIS_BULLETS_FOR_PISTOL 16
#define CLASS_RIFLEMAN 0
#define CLASS_SUPPORT 2
